ENT-787] Add support for update potransaction
Negotiatus/intacct-ruby pull request #5
Opened 2020-10-27 21:14 UTC by hoodr

Ticket: [ENT-787](https://negotiatus.atlassian.net/browse/ENT-787)

# Purpose
- Add support for `update_potransactoion` [#update-purchasing-transaction-legacy](https://developer.intacct.com/api/purchasing/purchasing-transactions/#update-purchasing-transaction-legacy)

# Changes
- Added `IntacctRuby::Function#parse_parameters` method to give IntacctRuby::Function to give it the ability to parse out xml attributes from the supplied parameters and add those attributes to the tag

2020-10-27 21:58 UTC, efmcuiti approved these changes

2020-10-28 15:30 UTC, sam-peach commented on lib/intacct_ruby/function.rb
> +    end
I'm too dumb for that `&& parameters.delete(XML_ATTRIBUTES)`
```suggestion
def parse_parameters(parameters)
  xml_attributes_present = parameters.is_a?(Hash) \
                            && parameters.include?(XML_ATTRIBUTES) \
                            && parameters[XML_ATTRIBUTES].is_a?(Hash) \

  xml_attributes = parameters.delete(XML_ATTRIBUTES) if xml_attributes_present

  [parameters, xml_attributes]
end
```

2020-10-28 15:31 UTC, sam-peach requested changes, later dismissed
Something to consider 🤷‍♂️

2020-10-28 17:08 UTC, sam-peach approved these changes

2020-10-28 18:47 UTC, merged